name: 'coverage'

on:
  pull_request:
    branches:
      - master
      - main

jobs:
  coverage:
    permissions:
      checks: write
      pull-requests: write
      contents: read
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: ArtiomTr/jest-coverage-report-action@v2
        with:
          working-directory: ./hello-world
      - name: Deploy
        run: |
          for BUCKET_NAME in s3-bucket1 s3-bucket2; do
            echo $BUCKET_NAME
          done
