name: 'coverage'

on:
  pull_request:
    branches:
      - master
      - main

jobs:
  checkout:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1

  coverage_hello-world:
    runs-on: ubuntu-latest
    needs: checkout
    defaults:
      run:
        working-directory: ./hello-world
    permissions:
      checks: write
      pull-requests: write
      contents: read
    steps:
      - uses: ArtiomTr/jest-coverage-report-action@v2

  coverage_calc:
    runs-on: ubuntu-latest
    needs: checkout
    defaults:
      run:
        working-directory: ./calc
    permissions:
      checks: write
      pull-requests: write
      contents: read
    steps:
      - uses: ArtiomTr/jest-coverage-report-action@v2
